package kucoinv1

import "github.com/msw-x/moon/ujson"

// ============================================================
// COMMON RESPONSE
// ============================================================

// OrderId - response for POST /api/v1/orders (Futures & Spot)
// https://www.kucoin.com/docs-new/rest/futures-trading/orders/add-order
type OrderId struct {
	// OrderId - The unique order id generated by the trading system
	OrderId string `json:"orderId"`
	// ClientOid - Unique order id created by users to identify their orders
	ClientOid string `json:"clientOid"`
}

// ============================================================
// FUTURES ORDER PLACEMENT
// ============================================================

// PlaceOrderFutures - request for POST /api/v1/orders (Futures API)
// https://www.kucoin.com/docs-new/rest/futures-trading/orders/add-order
type PlaceOrderFutures struct {
	// ClientOid - Unique order id created by users to identify their orders.
	// Only numbers, characters, underline(_) and separator(-) are allowed.
	ClientOid string `json:"clientOid"`
	// Side - Order side: "buy" or "sell"
	Side Side `json:"side"`
	// Symbol - Symbol of the contract (e.g., XBTUSDTM)
	Symbol string `json:"symbol"`
	// Leverage - Leverage of the order. Must be greater than 0 and less than or equal to maxLeverage
	// If CROSS margin mode this parameter is not required
	Leverage int `json:"leverage,omitempty"`
	// Type - Order type: "limit" or "market". Default is "limit"
	Type OrderType `json:"type,omitempty"`
	// Remark - Order remark. Max 100 utf8 characters
	Remark string `json:"remark,omitempty"`
	// Stop - Stop order type: "down" (trigger when price falls) or "up" (trigger when price rises)
	Stop string `json:"stop,omitempty"`
	// StopPriceType - Stop price type: "TP" (trade price), "IP" (index price), "MP" (mark price)
	StopPriceType StopPriceType `json:"stopPriceType,omitempty"`
	// StopPrice - Stop price for stop orders
	StopPrice string `json:"stopPrice,omitempty"`
	// ReduceOnly - Reduce only flag. If true, order will only reduce your position, not increase it
	ReduceOnly *bool `json:"reduceOnly,omitempty"`
	// CloseOrder - Close order flag. If true, closes the entire position
	CloseOrder *bool `json:"closeOrder,omitempty"`
	// ForceHold - Force hold flag for margin requirements
	ForceHold *bool `json:"forceHold,omitempty"`
	// Self Trade Prevention is divided into these strategies: CN, CO, CB. DC not currently supported.
	Stp string `json:"stp,omitempty"`
	// MarginMode - Account margin mode: "ISOLATED" or "CROSS". Required.
	MarginMode MarginMode `json:"marginMode,omitempty"`
	// Price - Limit price. Required for limit orders. Must be multiple of tickSize
	Price string `json:"price,omitempty"`
	// Size - Order size in contracts. Must be a positive integer
	Size int `json:"size,omitempty"`
	// Order size (base currency) must be an integer multiple of the multiplier.
	// Not supported for COIN-M.
	Qty string `json:"qty,omitempty"`
	// Order size (Value), USDS-Swap correspond to USDT or USDC.
	// Not supported for COIN-M.
	ValueQty string `json:"valueQty,omitempty"`
	// TimeInForce - Time in force: GTC (Good Till Canceled), IOC (Immediate Or Cancel), FOK (Fill Or Kill)
	TimeInForce TimeInForce `json:"timeInForce,omitempty"`
	// PostOnly - Post only flag. If true, order will only be added to the order book if it doesn't match immediately
	PostOnly *bool `json:"postOnly,omitempty"`
	// Hidden - Hidden order flag. If true, order will not be displayed in the order book
	Hidden *bool `json:"hidden,omitempty"`
	// Iceberg - Iceberg order flag. If true, only a portion of the order is displayed
	Iceberg *bool `json:"iceberg,omitempty"`
	// VisibleSize - The maximum visible size of an iceberg order
	VisibleSize string `json:"visibleSize,omitempty"`
	// PositionSide - Position direction: "BOTH", "LONG", or "SHORT".
	// Use "BOTH" for one-way mode, "LONG"/"SHORT" for hedge mode. BOTH - default
	PositionSide PositionSide `json:"positionSide,omitempty"`
}

func (o PlaceOrderFutures) Do(c *Client) Response[OrderId] {
	return Post(c, "orders", o, forward[OrderId])
}

func (o *Client) PlaceOrderFutures(v PlaceOrderFutures) Response[OrderId] {
	return v.Do(o)
}

// ============================================================
// FUTURES ORDER DETAILS
// ============================================================

// OrderFutures - response for GET /api/v1/orders/byClientOid (Futures API)
// https://www.kucoin.com/docs-new/rest/futures-trading/get-stop-order-by-clientoid
type OrderFutures struct {
	// Id - Order ID assigned by the system
	Id string `json:"id"`
	// Symbol - Symbol of the contract
	Symbol string `json:"symbol"`
	// Type - Order type: "limit" or "market"
	Type string `json:"type"`
	// Side - Order side: "buy" or "sell"
	Side string `json:"side"`
	// Price - Order price
	Price ujson.Float64 `json:"price"`
	// Size - Order size in contracts
	Size ujson.Int64 `json:"size"`
	// Value - Order value in settlement currency
	Value ujson.Float64 `json:"value"`
	// DealValue - Executed value in settlement currency
	DealValue ujson.Float64 `json:"dealValue"`
	// DealSize - Executed size in contracts
	DealSize ujson.Int64 `json:"dealSize"`
	// Stp - Self-trade prevention mode
	Stp string `json:"stp"`
	// Stop - Stop order type: "down" or "up"
	Stop string `json:"stop"`
	// StopPriceType - Stop price type: "TP", "IP", or "MP"
	StopPriceType string `json:"stopPriceType"`
	// StopTriggered - Whether stop order has been triggered
	StopTriggered bool `json:"stopTriggered"`
	// StopPrice - Stop trigger price
	StopPrice ujson.Float64 `json:"stopPrice"`
	// TimeInForce - Time in force: "GTC", "IOC", "FOK"
	TimeInForce string `json:"timeInForce"`
	// PostOnly - Whether order is post-only
	PostOnly bool `json:"postOnly"`
	// Hidden - Whether order is hidden
	Hidden bool `json:"hidden"`
	// Iceberg - Whether order is iceberg
	Iceberg bool `json:"iceberg"`
	// VisibleSize - Visible size for iceberg orders
	VisibleSize ujson.Int64 `json:"visibleSize"`
	// Leverage - Order leverage
	Leverage ujson.Float64 `json:"leverage"`
	// ForceHold - Whether force hold is enabled
	ForceHold bool `json:"forceHold"`
	// CloseOrder - Whether this is a close order
	CloseOrder bool `json:"closeOrder"`
	// ReduceOnly - Whether order is reduce-only
	ReduceOnly bool `json:"reduceOnly"`
	// ClientOid - Client order ID provided by user
	ClientOid string `json:"clientOid"`
	// Remark - Order remark
	Remark string `json:"remark"`
	// Tags - Order tags
	Tags string `json:"tags"`
	// IsActive - Whether order is still active (open)
	IsActive bool `json:"isActive"`
	// CancelExist - Whether cancel request exists for this order
	CancelExist bool `json:"cancelExist"`
	// CreatedAt - Order creation timestamp in milliseconds
	CreatedAt ujson.Int64 `json:"createdAt"`
	// UpdatedAt - Order last update timestamp in milliseconds
	UpdatedAt ujson.Int64 `json:"updatedAt"`
	// EndAt - Order end timestamp in milliseconds (when filled/cancelled)
	EndAt ujson.Int64 `json:"endAt"`
	// OrderTime - Order placement time in nanoseconds
	OrderTime ujson.Int64 `json:"orderTime"`
	// SettleCurrency - Settlement currency (e.g., "USDT")
	SettleCurrency string `json:"settleCurrency"`
	// Status - Order status: "match" (partially filled), "open", "done"
	Status OrderStatus `json:"status"`
	// FilledSize - Total filled size
	FilledSize ujson.Int64 `json:"filledSize"`
	// FilledValue - Total filled value
	FilledValue ujson.Float64 `json:"filledValue"`
	// MarginMode - Margin mode: "ISOLATED" or "CROSS"
	MarginMode string `json:"marginMode"`
	// PositionSide - Position side for hedge mode: "BOTH", "LONG", "SHORT"
	PositionSide string `json:"positionSide"`
	// AvgDealPrice - Average executed price
	AvgDealPrice ujson.Float64 `json:"avgDealPrice"`
}

// GetOrderFutures - request for GET /api/v1/orders/byClientOid (Futures API)
// https://www.kucoin.com/docs-new/rest/futures-trading/get-stop-order-by-clientoid
type GetOrderFutures struct {
	// ClientOid - The client order ID to retrieve
	ClientOid string `url:"clientOid"`
}

func (o GetOrderFutures) Do(c *Client) Response[OrderFutures] {
	return Get(c, "orders/byClientOid", o, forward[OrderFutures])
}

func (o *Client) GetOrderFutures(clientOid string) Response[OrderFutures] {
	return GetOrderFutures{ClientOid: clientOid}.Do(o)
}

// ============================================================
// SPOT ORDER PLACEMENT
// ============================================================

// PlaceOrderSpot - request for POST /api/v1/hf/orders (Spot API)
// https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-order
type PlaceOrderSpot struct {
	// ClientOid - Unique order id created by users to identify their orders.
	ClientOid string `json:"clientOid,omitempty"`
	// Symbol - Trading pair symbol (e.g., BTC-USDT)
	Symbol string `json:"symbol"`
	// Type - Order type: "limit" or "market"
	Type OrderType `json:"type"`
	// Side - Order side: "buy" or "sell"
	Side Side `json:"side"`
	// Stp - Self-trade prevention: "CN" (Cancel Newest), "CO" (Cancel Oldest), "CB" (Cancel Both), "DC" (Decrease and Cancel)
	Stp string `json:"stp,omitempty"`
	// Tags - Order identifier with max 20 ASCII characters
	Tags string `json:"tags,omitempty"`
	// Remark - Order remark. Max 20 ASCII characters
	Remark string `json:"remark,omitempty"`

	// Price - Limit price. Required for limit orders
	Price string `json:"price,omitempty"`
	// TimeInForce - Time in force: GTC, GTT (Good Till Time), IOC, FOK
	TimeInForce TimeInForce `json:"timeInForce,omitempty"`
	// CancelAfter - Cancel after n seconds. Requires timeInForce to be GTT
	CancelAfter int64 `json:"cancelAfter,omitempty"`
	// PostOnly - Post only flag. Order will be cancelled if it matches immediately
	PostOnly *bool `json:"postOnly,omitempty"`
	// Hidden - Hidden order flag. Order will not appear in order book
	Hidden *bool `json:"hidden,omitempty"`
	// Funds - Order amount in quote currency. For market buy orders only
	Iceberg *bool `json:"iceberg,omitempty"`
	// VisibleSize - The maximum visible size of an iceberg order
	VisibleSize string `json:"visibleSize,omitempty"`

	// Size - Order size in base currency (e.g., "0.001" for BTC)
	Size  string `json:"size,omitempty"`
	Funds string `json:"funds,omitempty"`
	// Iceberg - Iceberg order flag. Only a portion of the order is displayed
}

func (o PlaceOrderSpot) Do(c *Client) Response[OrderId] {
	cc := c.Copy().WithBaseUrl(SpotBaseUrl).WithPath("api/v1")
	return Post(cc, "hf/orders", o, forward[OrderId])
}

func (o *Client) PlaceOrderSpot(v PlaceOrderSpot) Response[OrderId] {
	return v.Do(o)
}

// ============================================================
// SPOT ORDER DETAILS
// ============================================================

// OrderSpot - response for GET /api/v1/hf/orders/client-order/{clientOid} (Spot HF API)
// https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-order-by-clientoid
type OrderSpot struct {
	// Id - Order ID assigned by the system
	Id string `json:"id"`
	// Symbol - Trading pair symbol (e.g., BTC-USDT)
	Symbol string `json:"symbol"`
	// OpType - Operation type: "DEAL" (matched) or "CANCEL" (cancelled)
	OpType string `json:"opType"`
	// Type - Order type: "limit" or "market"
	Type string `json:"type"`
	// Side - Order side: "buy" or "sell"
	Side string `json:"side"`
	// Price - Order price
	Price ujson.Float64 `json:"price"`
	// Size - Order size in base currency
	Size ujson.Float64 `json:"size"`
	// Funds - Order funds in quote currency
	Funds ujson.Float64 `json:"funds"`
	// DealFunds - Executed funds in quote currency
	DealFunds ujson.Float64 `json:"dealFunds"`
	// DealSize - Executed size in base currency
	DealSize ujson.Float64 `json:"dealSize"`
	// Fee - Trading fee paid
	Fee ujson.Float64 `json:"fee"`
	// FeeCurrency - Currency of the trading fee
	FeeCurrency string `json:"feeCurrency"`
	// Stp - Self-trade prevention mode
	Stp string `json:"stp"`
	// TimeInForce - Time in force: "GTC", "GTT", "IOC", "FOK"
	TimeInForce string `json:"timeInForce"`
	// PostOnly - Whether order is post-only
	PostOnly bool `json:"postOnly"`
	// Hidden - Whether order is hidden
	Hidden bool `json:"hidden"`
	// Iceberg - Whether order is iceberg
	Iceberg bool `json:"iceberg"`
	// VisibleSize - Visible size for iceberg orders
	VisibleSize ujson.Float64 `json:"visibleSize"`
	// CancelAfter - Cancel after n seconds (for GTT orders)
	CancelAfter ujson.Int64 `json:"cancelAfter"`
	// Channel - Order channel (e.g., "API")
	Channel string `json:"channel"`
	// ClientOid - Client order ID provided by user
	ClientOid string `json:"clientOid"`
	// Remark - Order remark
	Remark string `json:"remark"`
	// Tags - Order tags
	Tags string `json:"tags"`
	// Active - Whether order is still active (open)
	Active bool `json:"active"`
	// InOrderBook - Whether order is in the order book
	InOrderBook bool `json:"inOrderBook"`
	// CancelExist - Whether cancel request exists for this order
	CancelExist bool `json:"cancelExist"`
	// CreatedAt - Order creation timestamp in milliseconds
	CreatedAt ujson.Int64 `json:"createdAt"`
	// LastUpdatedAt - Order last update timestamp in milliseconds
	LastUpdatedAt ujson.Int64 `json:"lastUpdatedAt"`
	// TradeType - Trade type: "TRADE", "MARGIN_TRADE", or "MARGIN_ISOLATED_TRADE"
	TradeType string `json:"tradeType"`
	// CancelledSize - Cancelled size
	CancelledSize ujson.Float64 `json:"cancelledSize"`
	// CancelledFunds - Cancelled funds
	CancelledFunds ujson.Float64 `json:"cancelledFunds"`
	// RemainSize - Remaining size
	RemainSize ujson.Float64 `json:"remainSize"`
	// RemainFunds - Remaining funds
	RemainFunds ujson.Float64 `json:"remainFunds"`
	// Tax - Tax amount
	Tax ujson.Float64 `json:"tax"`
	// CancelReason - Reason code for cancellation
	CancelReason ujson.Int64 `json:"cancelReason"`
}

// GetOrderSpot - request for GET /api/v1/hf/orders/client-order/{clientOid} (Spot HF API)
// https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-order-by-clientoid
type GetOrderSpot struct {
	// ClientOid - The client order ID to retrieve
	ClientOid string
	// Symbol - Trading pair symbol (required for HF orders)
	Symbol string `url:"symbol"`
}

func (o GetOrderSpot) Do(c *Client) Response[OrderSpot] {
	cc := c.Copy().WithBaseUrl(SpotBaseUrl).WithPath("api/v1")
	return Get(cc, "hf/orders/client-order/"+o.ClientOid, o, forward[OrderSpot])
}

func (o *Client) GetOrderSpot(clientOid, symbol string) Response[OrderSpot] {
	return GetOrderSpot{ClientOid: clientOid, Symbol: symbol}.Do(o)
}
